// <auto-generated />
using System;
using CarsInsideGarage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarsInsideGarage.Migrations
{
    [DbContext(typeof(GarageDbContext))]
    [Migration("20260210171237_SchemaRemake")]
    partial class SchemaRemake
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("CarsInsideGarage.Data.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.ToTable("Cars", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LicensePlate = "ABC123"
                        },
                        new
                        {
                            Id = 2,
                            LicensePlate = "XYZ789"
                        },
                        new
                        {
                            Id = 3,
                            LicensePlate = "LMN456"
                        });
                });

            modelBuilder.Entity("CarsInsideGarage.Data.Entities.Garage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GarageFeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GarageFeeId");

                    b.HasIndex("LocationId")
                        .IsUnique();

                    b.ToTable("Garages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 150,
                            GarageFeeId = 1,
                            LocationId = 1,
                            Name = "Uptown Garage"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 60,
                            GarageFeeId = 2,
                            LocationId = 2,
                            Name = "Downtown Garage"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 200,
                            GarageFeeId = 1,
                            LocationId = 3,
                            Name = "Suburban Garage"
                        });
                });

            modelBuilder.Entity("CarsInsideGarage.Data.Entities.GarageFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DailyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("GarageFees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DailyRate = 20.00m,
                            HourlyRate = 2.00m,
                            MonthlyRate = 200.00m
                        },
                        new
                        {
                            Id = 2,
                            DailyRate = 40.00m,
                            HourlyRate = 4.00m,
                            MonthlyRate = 400.00m
                        });
                });

            modelBuilder.Entity("CarsInsideGarage.Data.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressCoordinates")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddressCoordinates")
                        .IsUnique();

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressCoordinates = "42.659892717892355, 23.315800826629413",
                            Area = "Center"
                        },
                        new
                        {
                            Id = 2,
                            AddressCoordinates = "42.66122100925116, 23.350871009687925",
                            Area = "Mladost"
                        },
                        new
                        {
                            Id = 3,
                            AddressCoordinates = "42.71897920798329, 23.276870966086467",
                            Area = "Lyulin"
                        });
                });

            modelBuilder.Entity("CarsInsideGarage.Data.Entities.ParkingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExitTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("GarageId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GarageId1")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCleared")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyRate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("GarageId");

                    b.HasIndex("GarageId1");

                    b.ToTable("ParkingSessions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountPaid = 5.00m,
                            CarId = 1,
                            DailyRate = 0m,
                            EntryTime = new DateTime(2024, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ExitTime = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageId = 1,
                            HourlyRate = 0m,
                            IsCleared = true,
                            MonthlyRate = 0m
                        },
                        new
                        {
                            Id = 2,
                            AmountPaid = 0.00m,
                            CarId = 2,
                            DailyRate = 0m,
                            EntryTime = new DateTime(2024, 2, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ExitTime = new DateTime(2024, 2, 2, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageId = 1,
                            HourlyRate = 0m,
                            IsCleared = false,
                            MonthlyRate = 0m
                        },
                        new
                        {
                            Id = 3,
                            AmountPaid = 25.00m,
                            CarId = 3,
                            DailyRate = 0m,
                            EntryTime = new DateTime(2024, 3, 3, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ExitTime = new DateTime(2024, 3, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            GarageId = 2,
                            HourlyRate = 0m,
                            IsCleared = true,
                            MonthlyRate = 0m
                        });
                });

            modelBuilder.Entity("CarsInsideGarage.Data.Entities.Garage", b =>
                {
                    b.HasOne("CarsInsideGarage.Data.Entities.GarageFee", "GarageFee")
                        .WithMany()
                        .HasForeignKey("GarageFeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarsInsideGarage.Data.Entities.Location", "Location")
                        .WithOne()
                        .HasForeignKey("CarsInsideGarage.Data.Entities.Garage", "LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GarageFee");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CarsInsideGarage.Data.Entities.ParkingSession", b =>
                {
                    b.HasOne("CarsInsideGarage.Data.Entities.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarsInsideGarage.Data.Entities.Garage", "Garage")
                        .WithMany()
                        .HasForeignKey("GarageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarsInsideGarage.Data.Entities.Garage", null)
                        .WithMany("Sessions")
                        .HasForeignKey("GarageId1");

                    b.Navigation("Car");

                    b.Navigation("Garage");
                });

            modelBuilder.Entity("CarsInsideGarage.Data.Entities.Garage", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
